### ISSUE TITLE
UnicodeDecodeError in /apispec_1.json

### ISSUE THREAD

**Issue by fernandochimi** [rochacbruno/flasgger#156]
An error ocurred in docs when I put characters with "ç", "ã", etc.
`UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 844: ordinal not in range(128)
  File "flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "flask/_compat.py", line 33, in reraise
    raise value
  File "flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "flask/views.py", line 149, in dispatch_request
    return meth(*args, **kwargs)
  File "flasgger/base.py", line 229, in get
    endpoint=rule.endpoint, verb=verb
  File "flasgger/utils.py", line 318, in parse_docstring
    full_doc = load_from_file(swag_path, swag_type)
  File "flasgger/utils.py", line 295, in load_from_file
    return yaml_file.read()
  File "encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]`

**Comment by rochacbruno** [comment]
Hi, where exaclty are you putting those chars? in yaml file specs? in doctring specs? or other attribute? can you give an example?

**Comment by fernandochimi** [comment]
@rochacbruno I put in yml file, on parameters > schema > description

**Comment by SBillion** [comment]
I get the same if I let an accent anywhere in the yml.
@fernandochimi I know this is not a fix for this encoding error but maybe you should think to write your documentation in english only. It's always a best practice to write documentation in english because next developers using your API could not understand your language

**Comment by MedyG** [comment]
Same problem. I have a 'utf-8' encoding yml file where some chars is not pure english, when I use @swag_from('utils.yml'), I got the same error. 
So I review the code and find the code line 436 in `flasgger/utils.py`

>     try:
           with open(swag_path) as yaml_file:
               return yaml_file.read()

I add attr `encoding='utf-8'` into open() and I can swag the file encoded in `utf-8` now.
I don't think this is a nice way to solve this problem, but I hope that flasgger can support `encoding` attr.

Best wishes!

**Comment by AngelLiang** [comment]
Yeah! Thanks MedyG. I can use this successfully:

```Python
import yaml
from flasgger.utils import swag_from

@swag_from(yaml.load_all(open("path/to/file.yml"), encoding="utf-8"))
def view_function():
    pass
```

**Comment by javabrett** [comment]
I was unable to reproduce this even on Windows.  For Python 3.7 however I was able to get a character to be mis-read, probably as the UTF8 character was read in `cp1252` or similar.

I think there is an improvement to be made here and added a PR.  The current YAML file-read does not enforce the encoding, so is vulnerable to different Python versions and different platform decisions on default encoding.  Since YAML must always be Unicode, we should detect UTF8/16/32 according to the YAML 1.2 spec then read as that.
