### ISSUE TITLE
Disable swagger generation ?

### ISSUE THREAD

**Issue by noviceamateur** [rochacbruno/flasgger#211]
Is there any config to stop generating swagger documentation all together ?

**Comment by javabrett** [comment]
Try https://github.com/rochacbruno/flasgger/blob/6bdacbafd9aa84f6d6f319a5a84b6fb90cc2b5a6/examples/disable_swagger_ui.py#L22

**Comment by rochacbruno** [comment]
@noviceamateur can you confirm if that solved your problem?

**Comment by noviceamateur** [comment]
Yeah. It worked. But is there a way to disable the apidocs as well ? Not just the UI

**Comment by rochacbruno** [comment]
@noviceamateur there is no such option, because the whole point of this extension is to provide the APIdocs.

What is your use case?

```python
from flasgger import Swagger

if app.config['ENABLE_FLASGGER']:
    Swagger(app)

```

The above will register `Swagger` only if you have `ENABLE_FLASGGER` in your config, is that a workaround for you?

Let me know the use case then we can think about adding more options.

**Comment by noviceamateur** [comment]
Ya. This will work. Thanks.
