### ISSUE TITLE
Consider pip-tools for dependency management

### ISSUE THREAD

**Issue by lwm** [rochacbruno/flasgger#71]
Have you seen https://github.com/jazzband/pip-tools?

You keep your dependencies pinned (repeatable builds) and up to date easily.

I can take a stab at adding it if you agree.

**Comment by rochacbruno** [comment]
I like the idea, for some of my projects I use pyup.io, but in the case of Flasgger I don't know if this is needed.

we have a very small set of requirements:

https://github.com/rochacbruno/flasgger/blob/master/setup.py#L48-L52

```python
install_requires=[
    'Flask>=0.10',
    'PyYAML>=3.0',
    'jsonschema>=2.5.1',
    'mistune',
    'six>=1.10.0'
]
```
And as flasgger is a library we cannot pin specific versions, only minimum requirements because of that I used `>=`

Do you think only 5 requirements is worth to use that tool?

**Comment by lwm** [comment]
Fair enough! :+1:
