### ISSUE TITLE
Feature request: support headerless YAML files

### ISSUE THREAD

**Issue by dkharlan** [rochacbruno/flasgger#93]
Currently, the API docs endpoint will not show docs for endpoints using a separate file (via the `@swag_from` decorator) if the file does not have a `\n---` before the content.  **Validation still works fine for these; just the API docs are missing.**

In other words, this works:

```
Here's some header text explaining my web service.
---
tags:
  - "thing_doer"
summary: "Do a thing"
description: ""
consumes:
  - "application/json"
produces:
  - "application/json"

...
```

whereas neither of these will be listed under `/apidocs`:

```
---
tags:
  - "thing_doer"
summary: "Do a thing"
description: ""
consumes:
  - "application/json"
produces:
  - "application/json"

...
```

```
tags:
  - "thing_doer"
summary: "Do a thing"
description: ""
consumes:
  - "application/json"
produces:
  - "application/json"

...
```

**Comment by rochacbruno** [comment]
@dkharlan good catch we must fix this.

**Comment by schamp** [comment]
I can take a stab at this.

**Comment by schamp** [comment]
It looks like the problem is here:  https://github.com/rochacbruno/flasgger/blob/6710a6e05217ae89810a445ee3f1bd6e672688a1/flasgger/utils.py#L497

It appears to assume that there will be a file header, if there's not, the "---" gets passed over looking for the first "\n" and it is not found, and the code assumes there is no YAML, just a docstring.

I believe the correct approach is to skip looking for that first "\n" and just looked for "---".  If the "---" is present, that indicates the first part is the summary description, and treat everything after the "---" as YAML.  If there is no "---", but it's from an external file, assume it's all YAML and try to parse that.  If there is no "---" and it's not from an external file, assume it's not YAML, just a docstring.
